### ISSUE TITLE
INKAs ønskeliste, sommer 2017 (meta)

### ISSUE THREAD

**Issue by neic** [TK-IT/regnskab#31]
INKA har sendt nedenstående ønskeliste i prioriteret rækkefølge til Rav.

- [x] Hvis det også kan blive mulig at sortere i listen af personer efter andet end navn, ville det være perfekt. F.ex. ved at trykke øverst på "øl" for at se hvem der har krydset flest/færrest øl (tryk en gang= fra mest til mindst, tryk to gange=fra mindst til mest).
- [ ] I krydslisten fra 2017-04-03 til 2017-04-10 blev en stor indgang delt i to små. Jeg ved ikke det er noget man kan kode sig udenom at sker.
- [ ] I krydslisten fra 2017-06-26 til 2017-07-01 blev to indgange læst som én. Måske kunne man kode sig udenom at det sker igen.
- [x] Når jeg printer krydslister vil jeg gerne kunne vælge at printe mere end en af gangen.

- [x] Når jeg skal indtaste "Andet"-beløb kommer der op en masse folk der ikke er på krydslisten. Disse behøver ikke stå der. Læs: De må godt komme op under "Tilføj betalinger", men kommer ikke til at få betale noget over krydslisten og kan derfor udeblive fra "Andet"-fanden.
- [x] Kan der gøres sådan at aliaser ikke er case-sensitive, lige som titler? I starten var det forvirrende at nogle aliaser har lutter versaler, mens andre kun har stor forbogstav. Det er nemlig ikke altid hængerene selv følger disse rætningslinier.
- [ ] Kan det på de små indgange være kun en række med krydser der anviser hvor mange krydser der er registreret, istedenfor at det også her er to?
- [ ] Regningen må gerne justeres en lille smule. Hvis begge kolonner kunne flyttes 2 mm ind mod midten giver det mere plads til at tape ude i siden uden at komme ovre i signeringsfeltet. Derudover ville det være lækkert hvis der var lige så meget plads nederst på siden som det er øverst lige nu, sådan at jeg kan placcere en tape-bid mellom to ark uden at det går hen over signeringsfeltet. Det kan måske gøres ved at gøre alle indgangene en lille smule mindre.
- [ ] En lille advarsel efter man har endret noget (f.ex. i hovedvinduet når man ændrer i hvad der skal stå i mailen) og går væk fra vinduet. Den kunne spørge om "er du sikker på at du vil væk fra dette vinduet? Dine ændringer er ikke gemt". K^nINKA kunne jo være lige så stor en idiot som mig.
- [ ] Findes der en måde hvor der kommer til at stå "Kære INKA (Halvor Høen Hval)", både i mails og på regningen. Altså tittel/alias i fed og menneskenavn i parentes? Jeg synes det kunne være nemmere at overskue.
- [ ] Er det en mulighed for at tjekke for entydighed hvis der kommer en ny Lene/Ninni/Laura/Lauge på krydslisten? Man kan ikke forvente at disse personer har styr på om der f.ex. kommer en ny FU der hedder det samme, og deres navn derfor ikke længere er entydigt. I kan lige tænke over det, jeg klarer ikke lige umiddelbart at komme op med en måde det kan gøres på.
- [x] Findes der en mulighed for at tegn som "^" hoppes over når man skriver det ind på krydslisteopgørelserne? På samme måde som at man med gamle titler kan skrive "T2OFORM" mens det stadig væk står som opløftet 2-tal på regningen. Det skal gerne være sådan at man kan skrive lige præcis de bogstaver/tal der står på krydslisten, uden at skulle "kode" når man aflæser og afskriver krydslisten. F.ex med Johannes alias K^nLÆGE vil det være fornemt at kunne skrive KnLÆGE istedenfor. Hvis det er muligt så vi det kunne give nogle sjove aliaser. Dog er dette ikke specielt vigtig, og hvis det er bøvlet så beder jeg hende finde et nyt alias, så ikke andre får lyst til at have lignende aliaser.

**Comment by Mortal** [comment]
Jeg har kodet lidt i dag og fikset nogle ting. Jeg har testet det lokalt, men ikke deployet det. (Man må gerne deploye master-branchen når man deployer Django 1.11.) Jeg har kun nået nogen af tingene:


* Implementeret sortering i alle "forbrugstabeller" (PurchaseStatsTable)
* Tilføjet "Copies"-felt når man udskriver krydslister
* Skjuler folk ikke på krydslisten når man indtaster "Andet"
* Søgning på aliaser er ikke case-sensitiv
* Søgning på aliaser springer `^` over
* Regningen delvist justeret: Vandrette margener er ændret, men jeg kunne ikke få de lodrette margener til at gøre som jeg vil.

* Jeg mangler at kigge på de to krydslister der blev indlæst forkert
* Jeg mangler at rette kryds-anvisningen for små indgange
* Jeg mangler at indsætte en advarsel når man forlader siden uden at gemme
* Jeg mangler at fikse fed titel / parentes-navn i mail
* Jeg mangler at lave noget til at opdage tvetydighed for gamle mennesker når nye kommer til

**Comment by Mortal** [comment]
Resterende ting på ønskelisten er flyttet til https://github.com/TK-IT/web/issues/188 og https://github.com/TK-IT/web/issues/189
